version: '3.7'

services:
  liferay:
    build: .
    image: gradle-liferay
    environment:
      LIFERAY_SETUP_PERIOD_WIZARD_PERIOD_ENABLED: "false"
      LIFERAY_TERMS_PERIOD_OF_PERIOD_USE_PERIOD_REQUIRED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_ENABLED: "false"
      LIFERAY_USERS_PERIOD_REMINDER_PERIOD_QUERIES_PERIOD_CUSTOM_PERIOD_QUESTION_PERIOD_ENABLED: "false"
    ports:
      - "8080:8080"
      - "5005:5005"
    volumes:
      - ./agp:/opt/agp/
      - ./deploy:/opt/liferay/deploy
      - ./liferay:/etc/opt/liferay
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8080/c/portal/layout" ]
      start_period: 1m
      interval: 1m
      retries: 3